name: lbricool
description: "lbricool project - design thinking"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
#  image_picker: ^1.1.2
  flutter_datetime_picker_plus: ^2.2.0
  font_awesome_flutter: ^10.8.0
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  intl: ^0.20.2
  file_picker: ^9.2.1
  http: ^1.3.0
  firebase_app_check: ^0.3.2+4
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - images/
   - assets/noto_money-bag.png
   - assets/images/

