name: lbrikol
description: "lbrikol project - design thinking"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter_custom_clippers: ^2.1.0
  smooth_page_indicator: ^1.2.1
  #  image_picker: ^1.1.2
  flutter_datetime_picker_plus: ^2.2.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
